module:
  # module to unpack 
  from: ../../module/my-work.mod
  # desired file to pack module to
  # to: server/modules/loi-alpha-test.mod
  to: server/modules/loi-alpha-test.mod

hak:
  # directory of .hak files to unpack
  from: ../../hak/raw
  # directory of exploded assets
  to: ../../hak/src

# what operating system (win|linux|macos)
os: win

# do not change these
root: ../../module/src
temp: ../../module/src/temporary